# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.5
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: true
kind: frontend-and-server
labextension_name: jupyterlab_advanced_html_viewer_extension
project_short_description: HTML viewer with trust, refresh, marks and notes stored
    in the file
python_name: jupyterlab_advanced_html_viewer_extension
repository: https://github.com/stellarshenson/jupyterlab_advanced_html_viewer_extension
test: true

